### PR TITLE
update sign on policy export

### PR DESCRIPTION
**Pull request by pbish-prh**
Modified the app sign on policy export to include all of the policy data in a more digestible format.
Attached a rough PS script as an example, to parse the data from the export into a usable csv.
[OktaAppCleanup.zip](https://github.com/gabrielsroka/gabrielsroka.github.io/files/11899970/OktaAppCleanup.zip)

### CODE REVIEW

**Comment by gabrielsroka** [comment]
thanks for your PR, i'm not going to use it.

**Comment by pbish-prh** [comment]
Okay!

Do you mind if I ask why? I know this is my first attempt at contributing to an open source project, but the current function exports nothing but the word “Priority” in the policies column, due to Okta’s weird table design. With this small change, my peers were able to export the data that they needed.
I don’t expect an answer, but I’m new to open source contributions I would very much appreciate knowing what I can do to make my contributions more meaningful.

Thanks!

Patrick

**Comment by gabrielsroka** [comment]
here's a powershell version

https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/OktaPrivateAPI.ps1

This calls a private API that can change so I don't want to write too much code against it because it will be brittle.

Also it's usually best to open an issue and coordinate with the repo owner before submitting a PR.

**Comment by pbish-prh** [comment]
Thank you for the information and the advice! I meant no offence.

Patrick

**Comment by gabrielsroka** [comment]
No offense taken.

**Pull request closed without merging**
