### PR TITLE
relocate rockstar popup

### PR DESCRIPTION
**Pull request by JasonBuckner**
Moves the main rockstar popup to the bottom left corner of the browser window. 
Addresses Issue #12 .
Other popups, such as 'API Explorer', still display in the upper left corner.

### CODE REVIEW

**Comment by gabrielsroka** [comment]
Hi @JasonBuckner 
did you test that change? the css you modified is commented out. 

instead, see
https://github.com/gabrielsroka/gabrielsroka.github.io/blob/master/rockstar/rockstar.js#L1188-L1193

**Comment by gabrielsroka** [comment]
also, have you tried using the minimize button `_` ?

**Comment by JasonBuckner** [comment]
Commented out? Well, that's embarrassing. Silly me.

**Comment by JasonBuckner** [comment]
The minimize button doesn't move the rockstar popup sufficiently to navigate to the hamburger menu on some resolutions. Simply put, it still doesn't move rockstar out of the way. 
I'll submit another PR.

**Comment by gabrielsroka** [comment]
this might help https://github.com/gabrielsroka/gabrielsroka.github.io/blob/master/rockstar/readme.md

> some resolutions
can you send a screen shot or provide more detail?

**Comment by JasonBuckner** [comment]
I use a vertical monitor configuration (1200x1920). The screenshots at #12 are helpful, but I find the default rockstar popup location (upper left corner) to be the most egregious when my browser is less than about 1303px in width. That's when the "hamburger" menu appears as seen at https://github.com/gabrielsroka/gabrielsroka.github.io/issues/12#issue-806630640.

**Comment by gabrielsroka** [comment]
makes sense. i don't have a good solution right now. you can disable rockstar and re-enable it just when u need. or close it when u need the hamburger menu (which is all the time -- that must be annoying). or use a different monitor. or modify rockstar (or its style) to better suit your use case. i designed it before the hamburger menu, and for landscape mode.

**Comment by JasonBuckner** [comment]
Moving the popup to the bottom of the browser seems a perfectly cromulent solution. 
Perhaps you could get fancy and _only_ move it when the detected window width is less than 1350 px.

**Pull request closed without merging**
